name: Auto update chart/resources

env:
  BTP_MANAGER_REPO: ${{ github.repository_owner }}/btp-manager
  SAP_BTP_SERVICE_OPERATOR_REPO: github.com/sap/sap-btp-service-operator
  GIT_EMAIL: team-gopher+1@sap.com
  GIT_NAME: kyma-btp-manager-bot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' 

jobs:
 
  auto-bump-chart:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Compare Tags
      run: |
        latest=$(scripts/update/get-latest-chart-version.sh)
        current=$(yq '.version' ./module-chart/chart/Chart.yaml)
        if [[ $latest == $current ]]; then
          echo "versions are the same: $latest=$current"
          echo "CONTINUE_JOB=false" >> $GITHUB_ENV
        else
          echo "version update from $current to $latest"
          echo "CONTINUE_JOB=true" >> $GITHUB_ENV
          echo "TAG=${latest}" >> $GITHUB_ENV
        fi

    - name: Update chart
      if: env.CONTINUE_JOB == 'true'
      run: scripts/update/make-module-chart.sh $TAG

    - name: Make templates
      if: env.CONTINUE_JOB == 'true'
      run: scripts/update/make-module-resources.sh $TAG

    - name: Configure Git
      if: env.CONTINUE_JOB == 'true'
      run: |
        git config --global user.email $GIT_EMAIL
        git config --global user.name $GIT_NAME
 
        echo "BRANCH_NAME=chart-$TAG" >> $GITHUB_ENV
        echo "MSG=Update module chart and resources to $TAG" >> $GITHUB_ENV

    - name: Check if there are changes
      if: env.CONTINUE_JOB == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        prs=$(gh pr list -A $GIT_NAME --state open --json headRefName | jq -r '.[] | .headRefName')
        if echo $prs | tr " " '\n' | grep -F -q -x $BRANCH_NAME; then
          echo "PR already exists, no need to create a new one"
          echo "CONTINUE_JOB=false" >> $GITHUB_ENV
        elif [ -z "$(git status --porcelain)" ]; then
          echo "nothing changed, skipping remaining steps"
          echo "CONTINUE_JOB=false" >> $GITHUB_ENV
        else
          echo "CONTINUE_JOB=true" >> $GITHUB_ENV
        fi

    - name: Pass changes
      if: env.CONTINUE_JOB == 'true'
      run: |
        git add module-chart/* 
        git add module-resources/* 
        git add controllers/btpoperator_controller.go
        git add config/rbac/role.yaml 
        git stash push --staged

    - name: Create PR
      if: env.CONTINUE_JOB == 'true'
      env:
        GH_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: scripts/update/create_pr.sh
