#  This GitHub action is designed to run end-to-end (e2e) tests on a Kubernetes cluster using the k3s distributions.
#  The action is triggered on pull requests to the main branch of the repository.

name: Run E2E tests on the cluster

env:
  LAST_K3S_VERSIONS: ${{ vars.LAST_K3S_VERSIONS }}

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  show-vars:
    name: Validate release
    runs-on: ubuntu-latest
    steps:
      - name: first
        run: |
          echo $LAST_K3S_VERSIONS
          echo ${{ vars.IMAGE_REPO }}
          echo ${{ secrets.JP_PESEL }}

  run-e2e-tests:
    uses: "./.github/workflows/run-e2e-tests-reusable.yaml"
    if: ${{ !github.event.pull_request.draft }}
    with:
      image-tag: PR-${{ github.event.number }}
      module-tag: v0.0.0-PR-${{ github.event.number }}
      image-repo: europe-docker.pkg.dev/kyma-project/dev/btp-manager
      module-repo: europe-docker.pkg.dev/kyma-project/dev/unsigned/component-descriptors/kyma.project.io/module/btp-operator
      skip-templates: --skip-templates
      credentials-mode: dummy
      last-k3s-versions: 3
