# Call this workflow from other jobs to execute unit tests in the current context

name: Run E2E tests on the cluster (reusable)

on:
  workflow_call:
    inputs:
      image-repo:
        description: Binary image registry reference
        required: true
        type: string
      module-repo:
        description: OCI module image registry reference
        required: true
        type: string
      image-tag:
        description: Binary image tag
        required: true
        type: string
      module-tag:
        description: OCI module image tag
        required: true
        type: string
      credentials-mode:
        description: real or dummy credentials
        required: true
        type: string
      skip-templates:
        description: wait for images only, skip template artifacts
        required: false
        type: string

jobs:
  prepare-tests:
    # job waits until Prow job uploads docker image, module OCI image and optionally artifacts
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.get-versions.outputs.k3s_versions }}
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: get-versions
        name: Get K3s versions
        run: |
          VERSIONS=($(./scripts/testing/get-latest-k3s-releases.sh 2))
          MATRIX_AS_JSON=$(echo ${VERSIONS[*]} | awk 'END {printf "{\"include\":[";for (i = 1; i < NF; i++) printf "{\"version\":%s},",$i;printf "{\"version\":%s}]}",$i }'|jq -c)
          echo "k3s_versions=${MATRIX_AS_JSON}" >> "${GITHUB_OUTPUT}"

      - name: Prepare K3s cluster and docker registry
        run: "./scripts/testing/k3s-setup.sh --wait"

      - name: Wait for artifacts
        env:
          BTP_OPERATOR_REPO: ${{ inputs.module-repo }}
          BTP_MANAGER_REPO: ${{ inputs.image-repo }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "./scripts/await_artifacts.sh ${{ inputs.image-tag }} ${{ inputs.module-tag }} ${{ inputs.skip-templates }}"

      - name: Install BTP operator
        env:
          SM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          SM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SM_URL: ${{ secrets.SM_URL }}
          SM_TOKEN_URL: ${{ secrets.TOKENURL }}
        run: "./scripts/testing/install.sh ${{ inputs.module-repo }}:${{ inputs.module-tag }} ${{ inputs.credentials-mode }} ci"

      - name: Run tests
        run: "./scripts/testing/run_e2e_module_tests.sh ${{ inputs.credentials-mode }} ci"

  run-e2e-tests:
    runs-on: ubuntu-latest
    needs: prepare-tests
    strategy:
      matrix: ${{ fromJSON(needs.prepare-tests.outputs.versions) }}
    steps:
      - name: Prepare K3s cluster and docker registry
        run: |
          echo ${{ matrix.version }}
          run: "./scripts/testing/k3s-setup.sh ${{ matrix.version }} --wait"